services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    environment:
      DATABASE_PATH: /data/db.sqlite3

    volumes:
      - backend_data:/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "8080:80"

    depends_on:
      - backend


volumes:
  backend_data: